# Data paths. Adjust to your actual data paths!
common:
  image_file: "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/calibration/image/0.bmp"
  pcd_file: "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/calibration/pcd/0.pcd"
  result_file: "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/extrinsic2.txt"

# Camera Parameters. Adjust as needed.
camera:
    camera_matrix: [910.623, 0.0,      651.66,
                    0.0,     910.183,  365.568,
                    0.0,     0.0,      1.0     ]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]  # 使用无畸变参数

calib:
  calib_config_file: "/home/cijh/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
  use_rough_calib: true

