# Data path. Adjust them!
common:
    image_path:  "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/calibration/image"
    pcd_path:  "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/calibration/pcd"
    result_path:  "/home/cijh/catkin_ws/src/my_project/data/calibration-20241113T112548Z-001/calibration/extrinsic.txt"
    data_num: 7  # 数据对数量（根据你的数据调整为实际数量）

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [910.623, 0.0,      651.66,
                    0.0,     910.183,  365.568,
                    0.0,     0.0,      1.0     ]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]  # 使用无畸变参数

# Calibration Parameters.!
calib:
    calib_config_file: "/home/cijh/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true  # 设置为 true，如果初始外参较差
